services:
  dev-db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    networks:
      - dev-network
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  dev-network:
